language: c

env:
  global:
    - LUAROCKS=2.4.3
  matrix:    
    - LUA=lua5.2 ZMQ_VER=4.2 LZMQ=lzmq
    - LUA=lua5.3 ZMQ_VER=4.2 LZMQ=lzmq
    - LUA=luajit ZMQ_VER=4.2 LZMQ=ffi-lua

branches:
  only:
    - master

before_install:
  - bash .travis/setup_lua.sh
  - if [ "$ZMQ_VER" == "4.2" ]; then
      bash .travis/setup_sodium.sh;
    fi
  - bash .travis/setup_zmq.sh

install:
  - sudo luarocks install luafilesystem
  - sudo luarocks install lua-path
  - sudo luarocks install lua-llthreads2
  - sudo luarocks install busted
  - sudo luarocks install luasocket

  - if [ $LZMQ = "ffi-lua" ]; then
      sudo luarocks install ljsyscall 0.9;
    fi

build_script:
  - sudo luarocks make

script:
  - cd test
